"""
github_pr.py - Real GitHub Pull Request Creator for CyberShield AI.

Uses the GitHub REST API (no external dependencies beyond `requests`) to:
  1. Get the repo's default branch SHA.
  2. Create a new security-patch branch.
  3. Commit the patched file onto that branch.
  4. Open a real Pull Request and return its URL.

Required .env variables:
  GITHUB_TOKEN   - Personal Access Token with `repo` scope
  GITHUB_OWNER   - GitHub username / org  (e.g. harkirat-data)
  GITHUB_REPO    - Repository name        (e.g. CyberShield-AI-Hackathon)
"""

from __future__ import annotations

import base64
import os
from typing import Any, Dict, Optional

try:
    import requests as _requests
    _REQUESTS_OK = True
except ImportError:
    _REQUESTS_OK = False


_GITHUB_API = "https://api.github.com"


def _headers(token: str) -> Dict[str, str]:
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _get(url: str, token: str) -> Dict[str, Any]:
    if not _REQUESTS_OK:
        raise RuntimeError("requests library not installed.")
    r = _requests.get(url, headers=_headers(token), timeout=15)
    r.raise_for_status()
    return r.json()


def _post(url: str, token: str, body: Dict[str, Any]) -> Dict[str, Any]:
    if not _REQUESTS_OK:
        raise RuntimeError("requests library not installed.")
    r = _requests.post(url, json=body, headers=_headers(token), timeout=15)
    r.raise_for_status()
    return r.json()


def _put(url: str, token: str, body: Dict[str, Any]) -> Dict[str, Any]:
    if not _REQUESTS_OK:
        raise RuntimeError("requests library not installed.")
    r = _requests.put(url, json=body, headers=_headers(token), timeout=15)
    r.raise_for_status()
    return r.json()


def create_github_pr(
    patch_info: Dict[str, Any],
    session_id: str,
    github_token: Optional[str] = None,
    owner: Optional[str] = None,
    repo: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Creates a real GitHub Pull Request using the GitHub REST API.

    Args:
        patch_info: Output dict from `generate_remediation_patch`.
        session_id: Honeypot session ID (used for branch suffix).
        github_token: GitHub PAT with `repo` scope.  Falls back to GITHUB_TOKEN env var.
        owner: GitHub repo owner.  Falls back to GITHUB_OWNER env var.
        repo: GitHub repo name.   Falls back to GITHUB_REPO env var.

    Returns:
        Dict with keys: html_url, head_branch, base_branch, pr_number, title, status
    """

    token = github_token or os.environ.get("GITHUB_TOKEN", "").strip()
    raw_repo = repo or os.environ.get("GITHUB_REPO", "CyberShield-AI-Hackathon").strip()
    raw_owner = owner or os.environ.get("GITHUB_OWNER", "").strip()

    if "/" in raw_repo and not raw_owner:
        owner_part, repo_part = raw_repo.split("/", 1)
        owner = owner_part.strip()
        repo = repo_part.strip()
    else:
        owner = raw_owner or "harkirat-data"
        repo = raw_repo or "CyberShield-AI-Hackathon"

    if not token:
        return _simulate_pr(patch_info, owner, repo, session_id,
                            error="GITHUB_TOKEN not configured in .env")

    pr_meta     = patch_info.get("git_pr", {})
    clean_sid   = session_id.replace("ses_", "")[:8]
    branch_name = pr_meta.get("branch", f"security/patch-{clean_sid}")
    target_file = pr_meta.get("target_file", "security_patch.py")
    pr_title    = pr_meta.get("title", "security: CyberShield AI Automated Patch")
    pr_body     = pr_meta.get("pr_body", "Automated security patch generated by CyberShield AI.")
    fixed_code  = patch_info.get("fixed_snippet", "# Automated security patch by CyberShield AI")

    base_url = f"{_GITHUB_API}/repos/{owner}/{repo}"

    try:
        # 1. Get default branch and its SHA
        repo_info   = _get(base_url, token)
        base_branch = repo_info.get("default_branch", "main")
        ref_info    = _get(f"{base_url}/git/ref/heads/{base_branch}", token)
        base_sha    = ref_info["object"]["sha"]

        # 2. Create new branch
        try:
            _post(f"{base_url}/git/refs", token, {
                "ref": f"refs/heads/{branch_name}",
                "sha": base_sha,
            })
        except Exception:
            # Branch might already exist – that's fine
            pass

        # 3. Commit the patched file onto the new branch
        file_content_b64 = base64.b64encode(fixed_code.encode("utf-8")).decode("utf-8")

        # Check if file already exists to get its SHA (update vs create)
        existing_sha: Optional[str] = None
        try:
            existing = _get(f"{base_url}/contents/{target_file}?ref={branch_name}", token)
            existing_sha = existing.get("sha")
        except Exception:
            pass

        commit_body: Dict[str, Any] = {
            "message": f"security: automated patch [{clean_sid}] - {pr_title}",
            "content": file_content_b64,
            "branch": branch_name,
        }
        if existing_sha:
            commit_body["sha"] = existing_sha

        _put(f"{base_url}/contents/{target_file}", token, commit_body)

        # 4. Open the Pull Request
        pr_response = _post(f"{base_url}/pulls", token, {
            "title": pr_title,
            "body": pr_body,
            "head": branch_name,
            "base": base_branch,
        })

        return {
            "status": "created",
            "html_url": pr_response["html_url"],
            "head_branch": branch_name,
            "base_branch": base_branch,
            "pr_number": pr_response["number"],
            "title": pr_title,
            "target_file": target_file,
            "owner": owner,
            "repo": repo,
            "error": None,
        }

    except Exception as exc:
        return _simulate_pr(patch_info, owner, repo, session_id, error=str(exc))


def _simulate_pr(
    patch_info: Dict[str, Any],
    owner: str,
    repo: str,
    session_id: str,
    error: str = "",
) -> Dict[str, Any]:
    """
    When no GITHUB_TOKEN is available or API calls fail, return a structured simulation
    with a link to the real GitHub compare page.
    """
    pr_meta     = patch_info.get("git_pr", {})
    clean_sid   = session_id.replace("ses_", "")[:8]
    branch_name = pr_meta.get("branch", f"security/patch-{clean_sid}")
    pr_title    = pr_meta.get("title", "security: CyberShield AI Automated Patch")
    target_file = pr_meta.get("target_file", "security_patch.py")

    compare_url = f"https://github.com/{owner}/{repo}/compare/main...{branch_name}?quick_pull=1"

    return {
        "status": "simulated",
        "html_url": compare_url,
        "head_branch": branch_name,
        "base_branch": "main",
        "pr_number": None,
        "title": pr_title,
        "target_file": target_file,
        "owner": owner,
        "repo": repo,
        "error": error or "GITHUB_TOKEN not set - showing compare link",
    }
